name: Delete RDP User
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'RDP Username to delete'
        required: true

jobs:
  delete:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Delete User
        shell: bash
        run: |
          userdel -r ${{ github.event.inputs.username }} || true
          echo "User ${{ github.event.inputs.username }} deleted successfully."
