name: Delete RDP User
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'RDP Username to delete'
        required: true

jobs:
  delete:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Delete User
        shell: bash
        run: |
          USERNAME=${{ github.event.inputs.username }}
          
          # ইউজারের সব প্রসেস জোর করে বন্ধ করা
          pkill -9 -u $USERNAME || true
          sleep 3
          
          # ভার্চুয়াল ডিস্ক আনমাউন্ট ও ডিলিট
          umount /home/$USERNAME || true
          rm -f /vps_storage/$USERNAME.img
          
          # ইউজার ডিলিট
          userdel -r $USERNAME || true
          
          echo "User $USERNAME deleted successfully."
